version: '3'
services:
  httpd:
    build:
      context: .
      dockerfile: Dockerfile.httpd
    container_name: httpd
    ports:
      - "8080:80"
    volumes:
      - "./test-page:/usr/local/apache2/htdocs/"
    restart: always