version: '3'
services:
  my-apache-app:
    image: httpd:2.4
    container_name: my-apache-app
    ports:
      - "8080:80"
    volumes:
      - "./test-page:/usr/local/apache2/htdocs/"
    restart: always