# Use official Node.js image
FROM node:latest

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY banking-app/package*.json ./

# Install dependencies
RUN npm install

# Copy application code
COPY ./banking-app .

# Expose port
EXPOSE 3000

# Command to run the application
CMD ["node", "index.js"]
