version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: node_bank
    volumes:
      - ./banking-app:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

